### ISSUE TITLE
the route-emitter build failed due to the vendor folder checkin.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry-incubator/uaa-go-client#11]
commit is : https://github.com/cloudfoundry-incubator/uaa-go-client/commit/3ef88f722de8878865db492a5353244ebb508b31

and the failure info is:
./main.go:301:39: cannot use logger (type "code.cloudfoundry.org/lager".Logger) as type "code.cloudfoundry.org/uaa-go-client/vendor/code.cloudfoundry.org/lager".Logger in argument to uaa_go_client.NewClient:
	"code.cloudfoundry.org/lager".Logger does not implement "code.cloudfoundry.org/uaa-go-client/vendor/code.cloudfoundry.org/lager".Logger (wrong type for Debug method)
		have Debug(string, ..."code.cloudfoundry.org/lager".Data)
		want Debug(string, ..."code.cloudfoundry.org/uaa-go-client/vendor/code.cloudfoundry.org/lager".Data)
./main.go:301:48: cannot use klok (type "code.cloudfoundry.org/clock".Clock) as type "code.cloudfoundry.org/uaa-go-client/vendor/code.cloudfoundry.org/clock".Clock in argument to uaa_go_client.NewClient:
	"code.cloudfoundry.org/clock".Clock does not implement "code.cloudfoundry.org/uaa-go-client/vendor/code.cloudfoundry.org/clock".Clock (wrong type for NewTicker method)
		have NewTicker(time.Duration) "code.cloudfoundry.org/clock".Ticker
		want NewTicker(time.Duration) "code.cloudfoundry.org/uaa-go-client/vendor/code.cloudfoundry.org/clock".Ticker

**Comment by zachgersh** [comment]
@andyliuliming - yeah, apologies for that. We are going to tweak this on master (so those dependencies aren't required for New). You'll see this on master soon.

**Comment by zachgersh** [comment]
@andyliuliming - this is now fixed by #12
