### ISSUE TITLE
Unclear if `DecodeToken()` checks for all or any of `desiredPermissions`

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-incubator/uaa-go-client#13]
`DecodeToken()` does not have any documentation stating whether it checks to ensure that *all* of the desired permissions are present or just any.

My assumption by reading the method signature is that all of the `desiredPermissions` must be present for this to return `nil`, however that's not what the code does (which will allow just any matching scope to pass).

ie  a call to `uaa.DecodeToken(token, "openid", "cloud_controller.admin")` will pass even if only the `openid` scope is present.

@drnic since I know he's looking at this area...

**Comment by adobley** [comment]
Hi @aeijdenberg,

We do plan to deprecate this library. You could be getting a token using the oauth2 library and decoding a token can be done with JWT and not using this library.

Sorry that its not a more helpful response.

**Comment by aeijdenberg** [comment]
Hi @adobley - given that deprecation is essentially just a documentation change (ie change the README.md to state "**This library is deprecated - please don't use in new projects**"), maybe it would be a good idea to bring that forward?

As it stands this looks like a recommended library for talking to UAA - and if the plan is to deprecate it, perhaps the sooner you let people know the better so that less people make it a dependency?

**Comment by emalm** [comment]
@adobley The diego-release repo also [uses this library](https://github.com/cloudfoundry/diego-release/tree/v2.21.0/src/code.cloudfoundry.org), so that the route-emitter can send TCP route registrations to the Routing API, so the Diego team would also be interested to know the recommended pathway forward if this library is (pre-?)deprecated.

/cc @jvshahid @goonzoid

**Comment by aeijdenberg** [comment]
@emalm - if you're using this library in prod, you might also be interested in https://github.com/cloudfoundry-incubator/uaa-go-client/issues/15#issuecomment-411601874 which was closed by this team who didn't feel it was important - it's quite lucky JWTs are validated correctly at all in current state.

**Comment by ndhanushkodi** [comment]
I think this warrants further discussion since this is being used across teams.

It'd be good to define a clear deprecation path, especially if we're using this library for TCP route registrations. 

/cc @rosenhouse @shubhaat @shalako @adobley 

Thanks.
Nitya and @utako

**Comment by mcwumbly** [comment]
We are closing this issue as `wontfix` and updating the README for this project to indicate that it is no longer maintained.

> # NOTICE
> 
> **This library is no longer maintained.**
> 
> Consider using the [`cloudfoundry-community/go-uaa`](https://github.com/cloudfoundry-community/go-uaa) client library instead.
