### ISSUE TITLE
`DecodeToken()` does not appear to contemplate signing key rotation

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-incubator/uaa-go-client#14]
Signed JWTs include a key ID (`kid` field). This can be used to identify the key used to sign the JWT and can help efficient verification of tokens.

Currently `DecodeToken()` appears to ignore this field, and try twice (fetching the latest key) upon failure.

Consider the case where token 1 (t1) is issued using key 1 (k1) and a few minutes later t2 is issued using a newly rotated k2.

If t2 is presented first, the resource server will never be able to validate t1 as UAA will no longer return k1 at the `/token_key` endpoint.

UAA appears to offer a `/token_keys` endpoint - it would be more appropriate to request this (rather than `/token_key`) and maintain a map of current public keys.

@drnic FYI

**Comment by adobley** [comment]
Hey @aeijdenberg 

As I mentioned in the [other issue](https://github.com/cloudfoundry-incubator/uaa-go-client/issues/13#issuecomment-436091475) we are planning to deprecate this library. I'm sorry that this isn't terribly helpful.

**Comment by ndhanushkodi** [comment]
Hey @aeijdenberg,

Given that we are trying to deprecate this library, we're going to close this issue at this point. Please feel free to reopen if you urgently need it.

Thanks!
Nitya and @utako
