### ISSUE TITLE
Logger with session not stored

### ISSUE THREAD

**Issue by BLaurent** [cloudfoundry-incubator/uaa-go-client#16]
Hi, 
looking at the logger, It's seems that the session is not taken in account? 
See
https://github.com/cloudfoundry-incubator/uaa-go-client/blob/ce6599d3f05c55c954834aff892c58e7b668fc70/client.go#L66

Should it be Instead ?
`
	logger = logger.Session("uaa-client")
`

Regards
B

**Comment by zachgersh** [comment]
@BLaurent - yeah, I think you are totally right.

We actually _may_ be interested in deprecating this actually library. What are you using it for?

**Comment by BLaurent** [comment]
Hi @zachgersh,
I am using this lib to handle all my uaa stuff in my cf services
There is a candidate replacement for it already, or is it planned ?
Regards
B

**Comment by aaronshurley** [comment]
@zachgersh is there a replacement candidate that you're aware of?

If not, then this _seems_ like a small enough change that we'd be happy to accept a PR for @BLaurent

**Comment by zachgersh** [comment]
@aaronshurley - going to depend on what @BLaurent is using:

token fetching - use the standard golang/oauth2 library
token validation - either use a JWT library or better yet, submit your token to UAA for validation (they have an endpoint for this).

**Comment by BLaurent** [comment]
@zachgersh @aaronshurley,
I use this library as a helper to get token from uaa to reach other services, checking token using DecodeToken.
Would you like me to create PR for this?
Regards

**Comment by zachgersh** [comment]
@BLaurent - nah, we still want to deprecate this. If your code is open source could you send it over? You should be getting a token using the oauth2 library (if you can). Decode a token can be done with JWT and not using this library.

**Comment by shubhaat** [comment]
@BLaurent just checking back on @zachgersh request above. If you can point us to your code, we could see if the replacements would work or a PR might be preferred.

**Comment by BLaurent** [comment]
@shubhaat Ok let me check If I can point you to the code I have. Otherwise do you need me to do smth else like a PR and do I need to sign any agreement of some kind ?
Regards

**Comment by jeffpak** [comment]
Hi @BLaurent ,

We're wondering if you found the code, or wrote a PR for this issue. Also, yes you should sign the CF CLA if you have not already.

Regards,
CF Routing Team

**Comment by mcwumbly** [comment]
We are closing this issue as `wontfix` and updating the README for this project to indicate that it is no longer maintained.

> # NOTICE
> 
> **This library is no longer maintained.**
> 
> Consider using the [`cloudfoundry-community/go-uaa`](https://github.com/cloudfoundry-community/go-uaa) client library instead.
