### ISSUE TITLE
Roadmap for other endpoints

### ISSUE THREAD

**Issue by burgerdev** [cloudfoundry-incubator/uaa-go-client#18]
Hi all,

good to see a go client for the UAA, thanks a lot! I'd be interested in your plans for supporting other functionality, in particular functions for the other OAuth2 token flows (Authorization Code, Refresh).

Cheers, Markus

**Comment by adobley** [comment]
Hi @burgerdev 

Unfortunately we do plan on deprecating this library, you could be getting a token using the oauth2 library and decoding a token can be done with JWT.

**Comment by ndhanushkodi** [comment]
Hey @burgerdev,

Given that we are trying to deprecate this library, we're going to close this issue at this point. Please feel free to reopen if you urgently need it.

Thanks!
Nitya and @utako
