### ISSUE TITLE
RegisterOauthClient creates a client, but returns nil

### ISSUE THREAD

**Issue by joeeltgroth** [cloudfoundry-incubator/uaa-go-client#19]
We used RegisterOauthClient to create a new client of type client_credentials.  The client was created in UAA, but we didn't get the information back.  This line https://github.com/cloudfoundry-incubator/uaa-go-client/blob/78298e618c027ca2a36fe6e49b000b47818416ea/client.go#L439 is looking for http response code OK (200), but the api call actually returns an http created (201).

**Comment by KauzClay** [comment]
Hi @joeeltgroth , 

Thanks for pointing this out. We have made the change.

Best,
@tcdowney and @KauzClay , CF Networking Program Members
