### ISSUE TITLE
JWT Claim issue?

### ISSUE THREAD

**Issue by mkreibe** [cloudfoundry-incubator/uaa-go-client#4]
I tried to compile this project but have this issue:

code.cloudfoundry.org/uaa-go-client/client.go:285: invalid operation: token.Claims["scope"](type jwt.Claims does not support indexing)

Is there a specific version of the 'github.com/dgrijalva/jwt-go' I should be using?

**Comment by shashwathi** [comment]
Hi @mkreibe 

Yes, looks like you have wrong version of `github.com/dgrijalva/jwt-go` library. Dependencies are not vendored and the right way to use `uaa-go-client` is as part of [routing release](https://github.com/cloudfoundry-incubator/routing-release). This will ensure `uaa-go-client` is compiled with right versions of dependencies.

I have updated README with better instructions to [setup](https://github.com/cloudfoundry-incubator/uaa-go-client#setup) uaa-go-client. 

Closing this issue for now and if you have any trouble using this library further please open a GH issue.

Regards
Shash
