### ISSUE TITLE
uaa-go-client contains two packages in the same directory - breaking some tools

### ISSUE THREAD

**Issue by kdykeman** [cloudfoundry-incubator/uaa-go-client#7]
We use [LicenseFinder](https://github.com/pivotal/LicenseFinder) to enumerate the open source dependencies in the CF code in order to generate OSLs. LicenseFinder runs `go list`, and in the case where there are two golang packages in the same directory (in this case 'uaa-go-client/examples'), `go list` fails with:
```
can't load package: package .: found packages fetch_key (fetch_key.go) and fetch_token (fetch_token.go) in workspace/uaa-go-client/examples
```
Can each package move into its own folder?

**Comment by jberkhahn** [comment]
Moved the examples into separate packages.

Hopefully this helps,
@jberkhahn and @flawedmatrix 
CF Routing Team
